<?php
/**
 * @file
 * Updating from D6 nj D7
 */

/**
 * I wanted to skip the cart and forward customers directly to the
 * checkout page, but then I needed some way to delete an item
 * from this page.
 *
 * (Icon is borrowed from "uc_removebutton")
 *
 */

/**
 * Implementation of hook_menu()
 * 
 * Add url for deleting cart item
 */
function uc_checkout_removebutton_menu() {
  $items = array();
  $items['cart/remove/%'] = array(
    'title' => 'Remove cart item',
    'access callback' => 'uc_checkout_removebutton_remove_cart_item',
    'access arguments' => array(2)
  );
  
  return $items;
}

/**
 * Remove cart item by id
 *  
 * @param int $item_id
 */
function uc_checkout_removebutton_remove_cart_item($data) {
    $items = uc_cart_get_contents();
    foreach ($items as $item){
        if (arg(2) == $item->cart_item_id) {
             uc_cart_remove_item($item->nid, $item->cart_id, $item->data);
                drupal_goto('cart/checkout');
        }  
    }
}
