<?php


/*
 * Implementation of hook_init()
 */

function cart_in_checkout_init() {
  drupal_add_js(drupal_get_path('module' , 'cart_in_checkout') . '/cart_in_checkout.js');
}


/**
 * Implementation of hook_menu().
 */
function cart_in_checkout_menu() {
  $items['update_cart/%'] = array(
    'title' => 'cart in checkout',
    'description' => 'Configure the payment settings.',
    'page callback' => 'cart_in_checkout_ajax_submit',
    'access arguments' => array('access content'),
  );
  return $items;
}

/*
 * implementation of hook_form_alter()
 */

function cart_in_checkout_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'uc_cart_checkout_form':
      $items = uc_cart_get_contents();
      $p['items'] = array('#type' => 'tapir_table' , '#tree' => TRUE);
      $i = 0;
      foreach ($items as $item) {
        $display_item = module_invoke($item->module, 'uc_cart_display', $item);

        if (!empty($display_item)) {
          $p['items'][$i] = $display_item;
          if (empty($display_item['qty'])) {
            $p['items'][$i]['qty'] = array(
              '#value' => '',
            );
          }

          $p['items'][$i]['total'] = array(
            '#value' => $item->total,
            '#theme' => 'uc_cart_view_price',
          );
          $i++;

        }
      }

      $form['panes']['cart']['cart_review_table'] = tapir_get_table('uc_cart_view_table', $p['items']);

      // add the price column
      $form['panes']['cart']['cart_review_table']['#columns']['price'] = array('cell' => 'Price' , 'weight' => 3);

      break;
  }

}


/*
 * added a submit function to update cart on checkout page
 */
function cart_in_checkout_ajax_submit() {
  $qty = explode("-" , arg(1));
  
  $items = uc_cart_get_contents();
  
  print_r($qty);
  foreach ($items as $k => $item) {
    $cart['items'][] = array(
      'nid' => $item->nid,
      'module' => 'uc_product',
      'qty' => $qty[$k]
    );
  }

      uc_cart_update_item_object((object)$cart);
      drupal_set_message("Your cart has been updated.");
  
  drupal_goto('cart/checkout');
  
}


/*
 * added a function to validate stock on cart update - will work only if out of stock module exists TODO - add this condition
 */
function ajax_cart_in_checkout_validate_form_addtocart($items) {
  $flag = 'no';
  //$items = $form_state['values']['panes']['cart']['cart_review_table'];
  // unserialize data
  foreach ($items as $k => $item) {
    // Validate unless the item was being removed
    if (!$item['remove']) {
      $data = unserialize($item['data']);
      $stockinfo = uc_out_of_stock_getstockinfo($item['nid'], $data['attributes']);
      $qty = $item['qty'];
      if ($stockinfo) {
        if ($stockinfo['stock'] - $qty < 0) {
          $error = _uc_out_of_stock_get_error('not_enough', $item['nid'], $data['attributes'], $stockinfo['stock'], $qty);
          $flag = 'yes';
          form_set_error("items][$k][qty", $error);
        }
      }
    }
  }
  return $flag;
}